#!/bin/csh
#
#
# shell script to run latex over the single top d0 note files
# twice to make sure all references are up to date and then
# producing a postscript file to view the output with all figures.
#
# 
# set up the TEXINPUTS path so that the revtex4 files can be found.
setenv TEXINPUTS ".:tex:tex/reconstruction:`pwd`/../revtex4:"

# run latex twice. latex is called from inside the runme script.
./runme.sh
./runme.sh
./runme.sh
# sleeping a little seems to help dvips
sleep 3

# force the postscript to be letter size.
dvips -t letter -o me_note.ps me_note.dvi
ps2pdf me_note.ps me_note.pdf
mv -f me_note.pdf ~/d0mino/public_html/d0_private/note.pdf
